name: GolangCI-Lint Compatibility

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    - cron: "0 0 * * 0" # Run weekly on Sundays at midnight

jobs:
  test-golangci-compat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          check-latest: true

      - name: Make script executable
        run: chmod +x ./scripts/test-golangci-compat.sh

      - name: Run compatibility tests
        run: ./scripts/test-golangci-compat.sh
